config/routes.rb
Rails.application.routes.draw do
  root 'photos#index'

  get "/search" => 'photos#search'
  resources :photos

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  def self.created_before(time)
    where("created_at < ?", time)
  end

  def self.newest_first
    order("created_at DESC")
  end

  def self.most_recent_five
    newest_first.limit(5)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
    #binding.pry
    @most_recent_photos = Photo.most_recent_five
    @created_before_photos = Photo.created_before(1.week.ago)
    if params[:search_value]
      @photos = Photo.where("title like ? or artist like ?", "%#{params[:search_value]}%", "%#{params[:search_value]}%")  
    else
      @photos = Photo.all
    end
  end

  def show
    @photo = Photo.find(params[:id])
  end

  def new
    @photo = Photo.new
  end

  def create
    @photo = Photo.new(photo_params)
    if @photo.save
      redirect_to photos_url
      #render :index # Render simply displays the index page, it does not do a new get request to /photos, and thus the photos#index method is never executed, and there is no @photos for the index.html.erb page to work with
    else
      render :new
    end
  end

  def edit
    @photo = Photo.find(params[:id])
  end

  def update
    @photo = Photo.find(params[:id])
    if @photo.update_attributes(photo_params)
      redirect_to "/photos/#{@photo.id}"
    else
      render :edit
    end
  end

  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy

    redirect_to photos_url
  end

#search based on full title of full author name
  # def search
  #   @search_results = Photo.all.select do |photo|
  #     if photo.attributes.values.include?(params[:value])
  #       photo
  #     end
  #   end
  # end
# search based on any work in any attribute

  private
  def photo_params
    params.require(:photo).permit(:artist, :title, :url)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Photogur2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/photos/edit.html.erb
<h1>Edit Picture</h1>

<p>
  <!-- <%= link_to "Back", photo_path(params[:id]) %> -->
  <%= link_to "Back", @photo %>
</p>

<%= form_for @photo do |f| %>
  <p>
    <%= f.label :artist %>
    <%= f.text_field :artist %>
  </p>
  <p>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :url %>
    <%= f.text_field :url %>
  </p>
  <p>
    <%= f.submit "Save" %>
  </p>
<% end %>

app/views/photos/index.html.erb
<h1>Photos</h1>
<%= link_to "New Photo", '/photos/new' %>

<%= form_tag root_path, method: :get do %>
  <%= label_tag :search_value, "Search by:" %>
  <%= text_field_tag :search_value, params[:search_value] %>
  <%= submit_tag "Search" %>
<% end %>

<%= link_to "View All", root_path %>

<h1>Most Recent (<%= @most_recent_photos.count %>)</h1>
<ul>
  <% @most_recent_photos.each do |photo| %>
  <li><%= link_to photo.title, photo_path(photo.id) %></li>
  <% end %>
</ul>

<h1>Created a Week ago (<%= @created_before_photos.count %>)</h1>
<ul>
  <% @created_before_photos.each do |photo| %>
  <li>link_to photo.title, photo_path(photo.id) </li>
  <% end %>
</ul>

<h1>Current (<%=@photos.count %>)</h1>
<% @photos.each do |photo| %>
  <p>
    <strong><%= photo.title %></strong>, by: <%= photo.artist %>
  </p>
  <%= link_to image_tag(photo.url), "/photos/#{photo.id}"%>
<% end %>

app/views/photos/new.html.erb
<h1>Add a Photo</h1>
<%= link_to "Back to Photos", photos_path %>
<!--Using photos_path instead or _url because we are in view and we don't need the full url, thats or controllers  -->

<%= form_for @photo do |f|%>
  <p>
    <%= f.label :artist %><br>
    <%= f.text_field :artist %>
  </p>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </p>
  <p>
    <%= f.submit "Save" %>
  </p>
<% end %>

app/views/photos/search.html.erb
<h1>Search Results</h1>

<% @search_results.each do |photo| %>
  <p>
    <strong><%= photo.title %></strong>, by: <%= photo.artist %>
  </p>
  <%= link_to image_tag(photo.url), "/photos/#{photo.id}"%>
<% end %>

app/views/photos/show.html.erb
<%= link_to "Back to Photos", photos_path %> | <%= link_to "Edit", edit_photo_path(@photo) %> | <%= link_to "Delete", @photo, method: :delete, data: {confirm: "Are you sure you want to delete this photo?"} %>





<p><%= @photo.title %>, <%= @photo.artist %></p>
<%= image_tag @photo.url %>